version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: ProjectManagementAPI/Dockerfile
    container_name: dotnet_api
    depends_on:
      - db
    ports:
      - "5225:5225"
    networks:
      - app_network
    restart: always

  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_DB: ProjectApi
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1123581321
    ports:
      - "5430:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network

networks:
  app_network:

volumes:
  postgres_data: